In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [6]:
narr = np.array(mylist)

In [9]:
type(narr)

numpy.ndarray

In [10]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
matrix = np.array(mylist)

In [12]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matrix.shape

(3, 3)

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.zeros(5)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((4,10))+1

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(5,5)

array([[0.11181779, 0.64990677, 0.96310121, 0.21866479, 0.82449337],
       [0.45296986, 0.68258615, 0.40027817, 0.24075942, 0.11989755],
       [0.01817483, 0.27702994, 0.41965284, 0.49992222, 0.34195543],
       [0.63383012, 0.98185176, 0.59869309, 0.06918984, 0.8149054 ],
       [0.80101109, 0.38922857, 0.55462878, 0.21799329, 0.38505331]])

In [25]:
np.random.randn(5,5)

array([[-0.2142315 ,  0.51679039, -1.43141233,  1.44319802, -1.53925993],
       [ 1.65880259, -0.70916824, -0.00962109,  0.49870529,  0.99499903],
       [ 0.05804814, -0.69484313,  0.1065375 , -0.01332129, -0.89206168],
       [-0.39061534, -0.170765  , -0.56630953,  0.10687772,  0.74855519],
       [ 0.44717468, -0.72814087,  2.02413125, -0.71157732, -0.44761138]])

In [26]:
np.random.normal(1,1,10)

array([2.19380204, 1.55317365, 1.95914905, 1.90459876, 1.28121781,
       1.4232389 , 3.44196769, 0.95076859, 0.92781073, 1.39428667])

In [28]:
np.random.randint(1,100,10)

array([86, 15, 40, 68, 36, 81, 47, 40, 56, 49])

In [29]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [33]:
arr.shape

(25,)

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()

43

In [38]:
ranarr.min()

1

In [40]:
ranarr.argmax()

3

In [41]:
ranarr.argmin()

1

In [42]:
ranarr.dtype

dtype('int64')

In [43]:
arr = np.arange(0,11)

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[:5]

array([0, 1, 2, 3, 4])

In [48]:
slice_of_array = arr[0:6]

In [50]:
slice_of_array[:] = 99

In [51]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [53]:
arr.copy()

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_2d = np.arange(5,46,5).reshape(3,3)

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[1,1]

25

In [65]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [66]:
arr = np.arange(1,11)

In [68]:
arr[arr<4]

array([1, 2, 3])

In [70]:
(arr + 100)/2

array([50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5, 55. ])

In [71]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [73]:
arr = arr-1

In [74]:
1/arr

/anaconda3/envs/tsa_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [75]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
np.log(arr)

/anaconda3/envs/tsa_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [77]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [79]:
arr.sum()

45

In [80]:
arr.mean()

4.5

In [81]:
arr_2d = np.arange(1,13,1).reshape(3,4)

In [82]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [84]:
arr_2d.sum(axis=1)

array([10, 26, 42])

### Excercises

In [85]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [88]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [90]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [94]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.random.rand()

0.6116531604882809

In [131]:
np.random.randn(25)

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152,
       -1.58457724, -0.64770677,  0.59857517,  0.33225003, -1.14747663,
        0.61866969, -0.08798693,  0.4250724 ,  0.33225315, -1.15681626,
        0.35099715, -0.60688728,  1.54697933,  0.72334161,  0.04613557,
       -0.98299165,  0.05443274,  0.15989294, -1.20894816,  2.22336022])

In [132]:
np.random.normal(0,1,25)

array([ 0.39429521,  1.69235772, -1.11281215,  1.63574754, -1.36096559,
       -0.65122583,  0.54245131,  0.04800625, -2.35807363, -1.10558404,
        0.83783635,  2.08787087,  0.91484096, -0.27620335,  0.7965119 ,
       -1.14379857,  0.50991978, -1.3474603 , -0.0093601 , -0.13070464,
        0.80208661, -0.30296397,  1.20200259, -0.19674528,  0.8365287 ])

In [100]:
np.linspace(0.01,1.,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [101]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [103]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [104]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [116]:
mat[3,4]

20

In [133]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [113]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [114]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [122]:
mat[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [123]:
mat.sum()

325

In [124]:
mat.std()

7.211102550927978

In [125]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [130]:
np.random.seed(4)
np.random.randint(1,2)

1