In [43]:
import numpy as np

In [ ]:
# METHODS

In [5]:
my_list = [1,2,3]

In [6]:
my_list

[1, 2, 3]

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
arr2 = np.array(my_mat)

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
randoml = np.random.rand(4)

In [26]:
np.random.randn(2)

array([-0.64397071,  0.9926924 ])

In [28]:
np.random.randint(1,100,10)

array([23, 10, 84, 80, 42, 99, 11, 74, 51, 51])

In [29]:
arr = np.arange(25)

In [30]:
ranarr = np.random.randint(0,50,10)

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr

array([20, 33, 22,  1, 24, 28, 23,  8, 28, 11])

In [32]:
ranarr.max()

33

In [33]:
ranarr.min()

1

In [34]:
ranarr.argmax()

1

In [39]:
arr=arr.reshape(5,5)

In [40]:
arr.shape

(5, 5)

In [42]:
randoml.dtype

dtype('float64')

In [44]:
# INDEXING

In [45]:
arr = np.arange(0,10)

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[9]

9

In [50]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[5:]

array([5, 6, 7, 8, 9])

In [53]:
arr[0:5]=100

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [55]:
arr=np.arange(0,10)

In [57]:
slicein=arr[0:5]

In [59]:
slicein

array([0, 1, 2, 3, 4])

In [63]:
slicein = slicein.copy()

In [62]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [65]:
arr_2d[0]

array([ 5, 10, 15])

In [67]:
arr_2d[1,2]

30

In [68]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [70]:
arr = np.arange(1,11)

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [75]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr[arr<3]

array([1, 2])

In [77]:
arr_2d = np.arange(50).reshape(5,10)

In [78]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [81]:
arr = np.arange(0,11)

In [82]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [86]:
arr/arr

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [87]:
1/arr

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [88]:
arr**arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [89]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])