In [1]:
#export
from exp.nb_02 import *
import torch.nn.functional as F

/Users/stanislavprihoda/anaconda3/envs/fastai/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/Users/stanislavprihoda/anaconda3/envs/fastai/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/stanislavprihoda/anaconda3/envs/fastai/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


### Initial setup

#### Data

In [2]:
mpl.rcParams['image.cmap']='gray'

In [3]:
x_trn,y_trn,x_val,y_val=get_data()

In [4]:
n,m=x_trn.shape
c=y_trn.max()+1
nh=50

In [6]:
class Model(nn.Module):
    def __init__(self,n_in,nh,n_out):
        super().__init__()
        self.layers = [nn.Linear(n_in,nh),nn.ReLU(),nn.Linear(nh,n_out)]
    def __call__(self,x):
        for l in self.layers:x=l(x)
        return x

In [7]:
model = Model(m,nh,10)

In [8]:
pred=model(x_trn)

### Crossentropy loss

In [9]:
def log_softmax(x): return (x.exp()/(x.exp().sum(-1,keepdim=True))).log()

In [10]:
sm_pred = log_softmax(pred)

In [11]:
sm_pred

tensor([[-2.5352, -2.3762, -2.1422,  ..., -2.3006, -2.1026, -2.2347],
        [-2.5055, -2.3965, -2.2156,  ..., -2.3553, -2.1166, -2.1940],
        [-2.3644, -2.3458, -2.2401,  ..., -2.3585, -2.2067, -2.3744],
        ...,
        [-2.4796, -2.1916, -2.2970,  ..., -2.3619, -2.2456, -2.2060],
        [-2.4294, -2.3237, -2.2744,  ..., -2.3576, -2.1969, -2.2106],
        [-2.5134, -2.2212, -2.3540,  ..., -2.3636, -2.2202, -2.2302]],
       grad_fn=<LogBackward>)

In [13]:
y_trn.shape

torch.Size([50000])

In [14]:
y_trn[:3]

tensor([5, 0, 4])

In [15]:
sm_pred[[0,1,2],[5,0,4]]

tensor([-2.2669, -2.5055, -2.1370], grad_fn=<IndexBackward>)

In [23]:
def nll(inp, target): return -inp[range(target.shape[0]),target].mean()

In [24]:
loss=nll(sm_pred,y_trn)

In [26]:
loss

tensor(2.3181, grad_fn=<NegBackward>)