In [192]:
import pandas as pd

In [193]:
df = pd.read_csv('iris.csv')

In [194]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [195]:
df.columns = ['sepal_length','sepal_width','petal_length','petal_width','target']

In [196]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2     0.0
1           4.9          3.0           1.4          0.2     0.0
2           4.7          3.2           1.3          0.2     0.0
3           4.6          3.1           1.5          0.2     0.0
4           5.0          3.6           1.4          0.2     0.0

In [197]:
df['target'] = df['target'].apply(lambda x:int(x))

In [198]:
y = df['target']

In [199]:
X = df[['sepal_length','sepal_width','petal_length','petal_width']]

In [200]:
from sklearn.model_selection import train_test_split

In [201]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [202]:
import tensorflow as tf

In [203]:
# FEATURE COLUMNS FOR ESTIMATOR

In [204]:
X.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [205]:
feat_cols=[]
for col in X.columns:
    feat_cols.append(tf.feature_column.numeric_column(col))

In [206]:
feat_cols

[_NumericColumn(key='sepal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sepal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [207]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=10,num_epochs=5,shuffle=True)

In [208]:
classifier = tf.estimator.DNNClassifier(hidden_units=[10,10],n_classes=3,feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/f9/jjw5gdz96wqb4d28dm_4kgt40000gn/T/tmpcee7j4wq', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x119187160>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [209]:
classifier.train(input_fn=input_func,steps=50)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/f9/jjw5gdz96wqb4d28dm_4kgt40000gn/T/tmpcee7j4wq/model.ckpt.
INFO:tensorflow:loss = 13.561649, step = 1
INFO:tensorflow:Saving checkpoints for 50 into /var/folders/f9/jjw5gdz96wqb4d28dm_4kgt40000gn/T/tmpcee7j4wq/model.ckpt.
INFO:tensorflow:Loss for final step: 3.976328.


In [210]:
pred_func = tf.estimator.inputs.pandas_input_fn(x=X_test,batch_size=len(X_test),shuffle=False)

In [211]:
prediction = list(classifier.predict(input_fn=pred_func))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/f9/jjw5gdz96wqb4d28dm_4kgt40000gn/T/tmpcee7j4wq/model.ckpt-50
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [212]:
prediction

[{'logits': array([-2.0182002 ,  0.59230316, -0.02588248], dtype=float32),
  'probabilities': array([0.04558217, 0.6201862 , 0.3342316 ], dtype=float32),
  'class_ids': array([1]),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ 2.4418457, -0.2999747, -3.6288273], dtype=float32),
  'probabilities': array([0.93741584, 0.06041918, 0.00216507], dtype=float32),
  'class_ids': array([0]),
  'classes': array([b'0'], dtype=object)},
 {'logits': array([-4.336723 ,  1.0262029,  1.5714612], dtype=float32),
  'probabilities': array([0.00171708, 0.36633512, 0.6319478 ], dtype=float32),
  'class_ids': array([2]),
  'classes': array([b'2'], dtype=object)},
 {'logits': array([-1.8807209 ,  0.489095  , -0.09570998], dtype=float32),
  'probabilities': array([0.05664096, 0.605799  , 0.33756   ], dtype=float32),
  'class_ids': array([1]),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([ 2.4083169 , -0.25730035, -3.5263774 ], dtype=float32),
  'probabilities': array([0.9326597

In [213]:
type(y_test)

pandas.core.series.Series

In [214]:
final_pred = []
for pred in prediction:
    final_pred.append(pred['class_ids'][0])

In [215]:
#final_pred

In [216]:
from sklearn.metrics import classification_report,confusion_matrix

In [217]:
print(confusion_matrix(y_test,final_pred))
print('----------------------------------')
print(classification_report(y_test,final_pred))

[[14  0  0]
 [ 0 15  1]
 [ 0  0 15]]
----------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

